movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('movies/', include('movies.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    about = models.TextField(blank=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)
    movie_image = models.ImageField(null=True, blank=True, upload_to='images/')

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from .models import Movie

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    return render(request, 'index.html', {'movies': movies})

def detail(request, movie_id):
    try:
        movie = Movie.objects.get(pk=movie_id)
        return render(request, 'detail.html', {'movie': movie})
    except Movie.DoesNotExist:
        raise Http404

vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

movies/templates/detail.html
{% extends "base.html" %}

{% block title %}About {{ movie.title }}{% endblock %}

{% block content %}
<dl>
    <dt>Title</dt>
    <dd>{{ movie.title }}</dd>
    <dt>Genre</dt>
    <dd>{{ movie.genre }}</dd>
    <dt>Release Year</dt>
    <dd>{{ movie.release_year }}</dd>
    <dt>About the movie</dt>
    <dd>{{ movie.about }}</dd>
    <dt>Image</dt>
    <dd>
        <section>
            <img class="banner" src="{{ movie.movie_image.url }}" alt="{{ movie.title }}">
        </section>
    </dd>
</dl>
{% endblock %}

movies/templates/index.html
{% extends 'base.html' %}

{% block title %}Movies{% endblock %}

{% block content %}
<br>
<div class="container-md">
    <h1 class="display-5">Our movies</h1>
    <p>Our collection of movies for you to choose. Scroll down if you must.</p>
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Release Year</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td>
                    <a class="link-offset-1" href="{% url "movies:detail" movie.id %}">{{ movie.title }}</a>
                </td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.release_year }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/about.html
{% extends "base.html" %}

{% block title %}About Us{% endblock %}

{% block content %}
<div class="front-top">
    <br>
    <div class="container shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="container text-center">
            <h1>About Vidly</h1>
        </div>

        <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi vero cupiditate soluta. Totam at
                temporibus adipisci dolore, accusantium officiis placeat a iusto veritatis vero in error praesentium
                doloremque. Nisi, dolore!</span><span>Libero, amet blanditiis. Esse amet, sed earum nobis dolores, iure
                nesciunt tempora quidem eligendi, necessitatibus tempore animi harum! Sequi aliquam in doloribus odio
                eius
                dignissimos explicabo! Quis provident dolores eligendi.</span><span>Veniam vel optio repellendus, iure
                dolores officiis! Magni accusamus ipsa praesentium dicta doloribus labore eos repellendus, eaque
                similique
                molestias, tempore fugit ducimus? Exercitationem praesentium quasi voluptatem tempore minima! Eligendi,
                magni?</span><span>Commodi hic incidunt eaque, mollitia, consequatur eveniet maxime eius dolorum enim
                labore
                provident dolore quis voluptas ullam sed ratione sit reprehenderit architecto. Harum vel cum nisi
                repellendus tempore doloribus dignissimos!</span><span>Fugiat delectus facilis voluptate! At similique
                recusandae, vero ut omnis nam! Suscipit quidem cumque corrupti placeat itaque praesentium debitis
                quisquam,
                porro repellat maiores. Sunt excepturi beatae accusantium error et labore?</span><span>Ratione esse
                quisquam
                quam vitae exercitationem ex alias qui deserunt expedita commodi? Placeat voluptate corporis accusamus
                unde,
                voluptas nesciunt reiciendis vel a vero beatae, deserunt, cumque optio! Dolor, ex ratione.</span>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam culpa, id vitae error, ut obcaecati delectus
            quos
            ipsa exercitationem accusamus inventore quas laboriosam amet. Nobis odio ab facilis beatae ex.
            Unde illum quae maxime voluptatem. Facilis sequi consequatur aliquid dolorem quisquam modi animi molestiae
            explicabo dolor, cum at id labore molestias quasi vitae veniam velit pariatur adipisci corrupti. Culpa,
            sunt.
            Incidunt dolores sit sapiente accusantium tempore quasi doloremque soluta, quas expedita earum ab
            necessitatibus
            exercitationem quis voluptatum alias architecto! Odio harum aperiam veniam minima nemo! Sed, harum
            quibusdam.
            Quae, laboriosam.
            Vel obcaecati iusto ipsa quam quaerat omnis vero maxime inventore architecto esse, sed fugiat officia
            maiores.
            Quos laudantium natus, perferendis tempora necessitatibus, atque minus, doloremque sint odit eius nesciunt
            iusto.
            Eos illum doloremque harum porro accusamus adipisci quasi atque tempore impedit. Corrupti inventore
            excepturi
            consequatur commodi mollitia quasi alias voluptate tempore quas tenetur animi eveniet, quisquam, numquam
            nobis
            necessitatibus dolor.
            Dolorem totam, quas quos at perspiciatis porro impedit quo est dignissimos delectus, quam iste inventore
            facere
            earum voluptate id? Deserunt obcaecati optio repellat sint numquam quo, ipsum voluptatum aut esse.
            Quasi accusantium repudiandae, distinctio quia nihil ratione excepturi voluptates soluta, repellendus rem
            officia maxime nemo neque? Provident delectus repellat, officia optio ratione autem magnam quae asperiores?
            Repellendus ducimus soluta illo.
        </p>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static from static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly | {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "styles.css" %}">
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Vidly</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about/">About</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
<header class="front-top">
    <div class="container">
        <div class=".bg-primary-subtle">
            <div id="carouselExampleCaptions" class="carousel slide">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                        aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                        aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                        aria-label="Slide 3"></button>
                </div>


                <div class="carousel-inner">

                    <div class="carousel-item active">
                        <!-- <img src="//Users//mehtaabkhan//Documents//Developer//Django_projects//vidly//images//SWAT.jpeg"
                            class="d-block w-100" alt="SWAT"> -->
                        <img src="media/images/SWAT.jpeg" class="d-block w-100 object-fit-fill border rounded img-fluid"
                            alt="SWAT" />
                        <div class="carousel-caption d-none d-md-block">
                            <h5>SWAT</h5>
                            <p>A group of Police has been recruited to join SWAT and face dangerous challenges ahead of
                                them
                                to keep balance in LA</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="media/images/speed.jpeg" class="d-block w-100 object-fit-fill border rounded"
                            alt="speed">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Second slide label</h5>
                            <p>Some representative placeholder content for the second slide.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="..." class="d-block w-100" alt="...">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>Third slide label</h5>
                            <p>Some representative placeholder content for the third slide.</p>
                        </div>
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>
</header>

<div class="container text-center">
    <p>Click <a href="movies/">movies</a> to check our entire collection of movies</p>
</div>

<p class="a_class">hello world</p>
{% endblock %}